/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/customerLogin`; params?: Router.UnknownInputParams; } | { pathname: `/deliveryLogin`; params?: Router.UnknownInputParams; } | { pathname: `/../components/shared/Visuals`; params?: Router.UnknownInputParams; } | { pathname: `/../components/shared/AnimatedHeader`; params?: Router.UnknownInputParams; } | { pathname: `/../components/shared/Header`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/delivery`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/customerLogin`; params?: Router.UnknownOutputParams; } | { pathname: `/deliveryLogin`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/shared/Visuals`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/shared/AnimatedHeader`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/shared/Header`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/delivery`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/customerLogin${`?${string}` | `#${string}` | ''}` | `/deliveryLogin${`?${string}` | `#${string}` | ''}` | `/../components/shared/Visuals${`?${string}` | `#${string}` | ''}` | `/../components/shared/AnimatedHeader${`?${string}` | `#${string}` | ''}` | `/../components/shared/Header${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `/delivery${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/customerLogin`; params?: Router.UnknownInputParams; } | { pathname: `/deliveryLogin`; params?: Router.UnknownInputParams; } | { pathname: `/../components/shared/Visuals`; params?: Router.UnknownInputParams; } | { pathname: `/../components/shared/AnimatedHeader`; params?: Router.UnknownInputParams; } | { pathname: `/../components/shared/Header`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/delivery`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
